### ISSUE TITLE
Question marks in X4HZ & Z9E5

### ISSUE THREAD

**Issue by bhajneet** [ShabadOS/database#1028]
| Key | Value |
| --- | ----- |
Source | Vaaran Bhai Gurdas Ji
Page | 10
ID | [X4HZ](https://database.shabados.com/sources/3/page/10/line/4)
Line | fufhuilkw mW puCY; qUM swvwxI hY ik surIqw? [
ID | [Z9E5](https://database.shabados.com/sources/3/page/10/line/6)
Line | iksu audm qy rwju imil; sqRU qy siB hovin mIqw? [

![image](https://user-images.githubusercontent.com/14130567/65391950-35fc9500-dd3d-11e9-8044-86f965f8ebe7.png)

**Comment by Sarabveer** [comment]
Should be removed and added to foonote #375
