### ISSUE TITLE
MGZC

### ISSUE THREAD

**Issue by bhajneet** [ShabadOS/database#1136]
| Key | Value |
| --- | ----- |
View | https://database.shabados.com/sources/3/page/41/line/5
Source | Vaaran Bhai Gurdas Ji
Page | 41
ID | MGZC
Line | guru ismr mnweI kwlkw; KMfy kI vylw [

![image](https://user-images.githubusercontent.com/14130567/65821215-93428b80-e200-11e9-82d1-f4f23250308e.png)

**Comment by bhajneet** [comment]
Note footnote. Which should we use? @Sarabveer

**Comment by Sarabveer** [comment]
Use `ਸਿਮਰਿ`, as its popular. Keep `ਦਾਸ` in footnotes. #375

**Comment by bhajneet** [comment]
![image](https://user-images.githubusercontent.com/14130567/65840154-58655400-e2e3-11e9-990e-56e2731147bf.png)

You want me to use the footnote in first source?

**Comment by Sarabveer** [comment]
Yes
