### ISSUE TITLE
NSQC

### ISSUE THREAD

**Issue by bhajneet** [ShabadOS/database#1157]
| Key | Value |
| --- | ----- |
View | https://database.shabados.com/sources/3/page/41/line/98
Source | Vaaran Bhai Gurdas Ji
Page | 41
ID | NSQC
Line | jh rwjySwh AmIrVy; hoey sB Cwrw [

![image](https://user-images.githubusercontent.com/14130567/65821739-c5a3b700-e207-11e9-8675-de2afcead3ea.png)

**Comment by Sarabveer** [comment]
`Swh` #375
