### ISSUE TITLE
BHUQ

### ISSUE THREAD

**Issue by bhajneet** [ShabadOS/database#1179]
| Key | Value |
| --- | ----- |
View | https://database.shabados.com/sources/3/page/41/line/127
Source | Vaaran Bhai Gurdas Ji
Page | 41
ID | BHUQ
Line | qh klmw koie n piVH skY; nhIN izkru Alwey [

![image](https://user-images.githubusercontent.com/14130567/65821859-621a8900-e209-11e9-86dd-233b420abd79.png)

**Comment by Sarabveer** [comment]
`izkru` #375
