### ISSUE TITLE
NQNF

### ISSUE THREAD

**Issue by bhajneet** [ShabadOS/database#1181]
| Key | Value |
| --- | ----- |
View | https://database.shabados.com/sources/3/page/41/line/129
Source | Vaaran Bhai Gurdas Ji
Page | 41
ID | NQNF
Line | Xih rwh SrIAq myt kir; muslm Brmwey [

![image](https://user-images.githubusercontent.com/14130567/65821867-84140b80-e209-11e9-857e-4df29701037e.png)

**Comment by Sarabveer** [comment]
`SrIAq` #375
