### ISSUE TITLE
ECJB

### ISSUE THREAD

**Issue by bhajneet** [ShabadOS/database#1189]
| Key | Value |
| --- | ----- |
View | https://database.shabados.com/sources/3/page/41/line/148
Source | Vaaran Bhai Gurdas Ji
Page | 41
ID | ECJB
Line | sB jg iqnhUM bs kIE; jp AlK Apwrw [

![image](https://user-images.githubusercontent.com/14130567/65821981-e3bee680-e20a-11e9-92c5-41fc77c4dfef.png)

**Comment by Sarabveer** [comment]
Related to #1190
