### ISSUE TITLE
VDKV

### ISSUE THREAD

**Issue by bhajneet** [ShabadOS/database#1203]
| Key | Value |
| --- | ----- |
View | https://database.shabados.com/sources/3/page/41/line/235
Source | Vaaran Bhai Gurdas Ji
Page | 41
ID | VDKV
Line | hirik®sn BXo; Astm bl bIrw [

![image](https://user-images.githubusercontent.com/14130567/65822144-25e92780-e20d-11e9-948e-4cb8e8a9d874.png)

**Comment by Sarabveer** [comment]
Should be left `hirik®sn`. Add to footnote #375
