### ISSUE TITLE
Double Line Endings in Ganj Nama Proof vs Single in Database Viewer

### ISSUE THREAD

**Issue by bhajneet** [ShabadOS/database#1251]
| Key | Value |
| --- | ----- |
View | https://database.shabados.com/sources/7/page/1/line/2
Source | Ganj Nama
Page | 1
ID | TF05
Line | sro &rkm iz rUie isdko s&w [1[

![image](https://user-images.githubusercontent.com/14130567/66845883-df026e00-ef3e-11e9-8874-3f953a400a5a.png)

**Comment by Sarabveer** [comment]
Keep as single danda

**Comment by Sarabveer** [comment]
also keep with single danda
