### ISSUE TITLE
AYHG

### ISSUE THREAD

**Issue by bhajneet** [ShabadOS/database#1272]
| Key | Value |
| --- | ----- |
View | https://database.shabados.com/sources/7/page/1/line/79
Source | Ganj Nama
Page | 1
ID | AYHG
Line | juz dir mn bjwnby nBrvMd [39[

![image](https://user-images.githubusercontent.com/14130567/66854276-095c2780-ef4f-11e9-8a31-919e72f7f3de.png)

**Comment by bhajneet** [comment]
I assume this should be `n-rvMd` like the line above it. They both had the same spelling prior `nBrvMd`. Let me know how to proceed.

**Comment by Sarabveer** [comment]
Yep, go with `n-rvMd`
