### ISSUE TITLE
Re-import Translations

### ISSUE THREAD

**Issue by Sarabveer** [ShabadOS/database#1342]
Current translations are either from iGurbani (which originally are from SearchGurbani) or from SearchGurbani itself.

They have various encoding errors and seem to be changed from the actual proof.

**Comment by bhajneet** [comment]
This issue seems too general/open.

Could you break it into smaller issues, such that each requires less than 10 hours of work to resolve?

**Comment by bhajneet** [comment]
Also is this a dupe of #1392?

**Comment by Sarabveer** [comment]
This is a duplicate of #1392. Closing
