### ISSUE TITLE
Unable to get languages when fetching translations/transliterations

### ISSUE THREAD

**Issue by Sarabveer** [ShabadOS/database#1356]
After updating GurbaniNow API to use v4.5.0, it errors.

https://dev-api.gurbaninow.com/v2/shabad/SNU
```js
{
	"error":true,
	"request": {
		"method":"GET",
		"path":"/v2/shabad/SNU",
		"query":{}
	},
	"message":"Cannot destructure property `language` of 'undefined' or 'null'."
}```

**Comment by Harjot1Singh** [comment]
Because it adds unnecessary overhead for the rest of users, I will not be adding it in by default, but 4.5.1 includes a parameter for modifying the translation/transliterations query, so if you modify your previous code as follows:

```
const getBaniLines = async baniId => Banis
  .query()
  .joinEager( 'lines.shabad' )
  .orderBy( [ 'line_group', 'lines.order_id' ] )
  .where( 'banis.id', baniId )
  .withTranslations( query => query.eager( 'translationSource.language' ) )
  .withTransliterations( query => query.eager( 'language' ) )
  .then( ( [ bani ] ) => bani )
```

**Comment by Harjot1Singh** [comment]
Is this resolved @Sarabveer?

**Comment by Sarabveer** [comment]
Yes.

https://github.com/GurbaniNow/api/commit/85b478530c0043782b0e027604731aaece1a9deb
https://github.com/GurbaniNow/api/commit/1b9182ed9c59ca1a332dc67550a03183c91ae2d3
