### ISSUE TITLE
Replace chars

### ISSUE THREAD

**Issue by Sarabveer** [ShabadOS/database#1374]
`` with `u`

`î` with `Î`

`!` with `,`

Examples:

`sB lwlc iqAwg dey igRh ky iek sÎwm ky pîwr kI hY su BuKI ]636]`

`crm idRsit mUd, pyKY idb idRsit kY; jgmg joiq, EnmnI suD pwveI [`

**Comment by Harjot1Singh** [comment]
These chars break `gurmukhi-utils@2.2.0`
