### ISSUE TITLE
Add Mahan Kosh dictionary / reference

### ISSUE THREAD

**Issue by bhajneet** [ShabadOS/database#1387]

**Comment by bhajneet** [comment]
_Originally Posted in Slack by @Harjot1Singh_

## Considerations

- [x] One definition to many words
- [x] One word to many definitions
- [x] Dekho smart-linking
- [ ] Font research

## Structure
```
{
   An: {
       definitions: ['definition1', 'definition2'],
       synonyms: []
   },
   Har: {
       definitions: ['definition4', 'definition5'],
       synonyms: ['Hari', 'Parmaatma']
   },
}
```
## Storage
`dictionaries/Mahan Kosh.json` etc

## Smart Linking
Automatically pick up "dekho" references and add the correct destination as a separate field in the database

## Output Transformation
`dictionary` table, with `dictionary_source_id` that references to another table, `dictionary_sources`

**Comment by bhajneet** [comment]
Duplicate #867

**Comment by Jaskaran100k** [comment]
hey i know searchgurbani.com have done which we were trying to do

**Comment by Jaskaran100k** [comment]
i am typing to convert pdf into api format openly

**Comment by bhajneet** [comment]
Hey, that's great to hear. Are you from the searchgurbani.com team?

**Comment by bhajneet** [comment]
Maybe we can discuss on #867
