### ISSUE TITLE
CGUS

### ISSUE THREAD

**Issue by Sarigpani** [ShabadOS/database#1394]
| Key | Value |
| --- | ----- |
View | https://database.shabados.com/sources/2/page/155/line/72
Source | Sri Dasam Granth
Page | 155
ID | CGUS
Line | <> **siqgur pRswid** ]
Correction | sRI vwihgurU jI kI Pqy

![image](https://user-images.githubusercontent.com/60820452/75609766-2b6fd400-5b03-11ea-9c3c-332852813c29.png)

**Comment by Sarabveer** [comment]
Did some research on this, seems like Dr. Rattan Singh Jaggi is the only one who deviates from this Mangal.

![image](https://user-images.githubusercontent.com/4297171/75613614-b9e15700-5afd-11ea-9fe6-b0ba64906e9e.png)

My personal view is that the mangal should be `ੴ ਵਾਹਿਗੁਰੂ ਜੀ ਕੀ ਫਤਹ ॥`

**Comment by Sarigpani** [comment]
I agree, I also checked this across various saroops. However, rather than ਫਤਹ its ਫਤੇ. I've checked this in  a few puratan saroops as well. For example from 1777:

![image](https://user-images.githubusercontent.com/60820452/75613938-fbd4c200-5b2a-11ea-9563-bd27125236b0.png)

**Comment by Sarabveer** [comment]
Probably depends on likhaari as well. ਫਤਹ is more widely used than ਫਤੇ.

**Comment by Sarigpani** [comment]
Yeah correct, it depends on the saroop. the above saroop I posted has both ਫਤਹ/ਫਤੇ in their respective places, Similarly, the fallback (mehron saroop) has both used as we can see. So we should stick to what they put in the particular mangal.

However, I've never heard about the Sri being a later addition, nor actually seen it avoided in any saroop. I'd be interested if you can find the Katha :)

**Comment by Sarabveer** [comment]
#95

**Comment by Sarigpani** [comment]
![image](https://user-images.githubusercontent.com/60820452/75713637-18efc900-5cc2-11ea-9396-db4afd8e294a.png)
![image](https://user-images.githubusercontent.com/60820452/75713662-23aa5e00-5cc2-11ea-9b53-1d278d93cb24.png)

This pothi has had sudhai done, and accordingly they have used each of the 4 types in the correct place.

**Comment by Sarabveer** [comment]
My main thinking comes from the fact that Fateh is a Perso-Arabic word, ਫ਼ਤਹ is technically how it's pronounced.

I tagged #95 so it can br added as another  variation. Default would be whatever is in the source.

**Comment by bhajneet** [comment]
![image](https://user-images.githubusercontent.com/14130567/77825128-bb427700-70dd-11ea-935a-fd65f54525ea.png)
