### ISSUE TITLE
RUXR

### ISSUE THREAD

**Issue by Sarigpani** [ShabadOS/database#1397]
| Key | Value |
| --- | ----- |
View | https://database.shabados.com/sources/2/page/155/line/75
Source | Sri Dasam Granth
Page | 155
ID | RUXR
Line | pwiqswhI 10 ]
Correction | move back one line, between Fate and Ath

![image](https://user-images.githubusercontent.com/60820452/75609856-f44df280-5b03-11ea-8ed1-b1d02a0e8d6a.png)

**Comment by bhajneet** [comment]
![image](https://user-images.githubusercontent.com/14130567/77825629-dfec1e00-70e0-11ea-92fb-2c803bd35a64.png)

Also changed to `pwqswhI 10`
