### ISSUE TITLE
VXHK

### ISSUE THREAD

**Issue by Sarigpani** [ShabadOS/database#1399]
| Key | Value |
| --- | ----- |
View | https://database.shabados.com/sources/2/page/155/line/77
Source | Sri Dasam Granth
Page | 155
ID | VXHK
Line | Ab caubIs **aucrO** Avqwrw ]
Correction | aucroN

![image](https://user-images.githubusercontent.com/60820452/75609900-7c33fc80-5b04-11ea-9dae-1c46a3eae4d7.png)

**Comment by bhajneet** [comment]
![image](https://user-images.githubusercontent.com/14130567/77825686-51c46780-70e1-11ea-802c-491c331b47c6.png)
