### ISSUE TITLE
NMQJ

### ISSUE THREAD

**Issue by Sarigpani** [ShabadOS/database#1402]
| Key | Value |
| --- | ----- |
View | https://database.shabados.com/sources/2/page/155/line/80
Source | Sri Dasam Granth
Page | 155
ID | NMQJ
Line | brnq sÎwm jQwmiq BweI ]1]

![image](https://user-images.githubusercontent.com/60820452/75611694-ca50fc00-5b14-11ea-8e34-818863323535.png)

**Comment by bhajneet** [comment]
Depends on https://github.com/GurbaniNow/gurmukhi-fonts/issues/9
