### ISSUE TITLE
TZHD

### ISSUE THREAD

**Issue by Sarigpani** [ShabadOS/database#1406]
| Key | Value |
| --- | ----- |
View | https://database.shabados.com/sources/2/page/155/line/86
Source | Sri Dasam Granth
Page | 155
ID | TZHD
Line | AMq kwil soeI Kwpinhwrw ]

<!-- Add details & attach image(s) below. Provide context & indication. Example: 
![image](https://user-images.githubusercontent.com/60820452/75611920-abec0000-5b16-11ea-8c96-0eb2c7ed6628.png)

**Comment by Sarigpani** [comment]
![image](https://user-images.githubusercontent.com/60820452/75611939-eeadd800-5b16-11ea-9afd-100467ec219f.png)

**Comment by bhajneet** [comment]
![image](https://user-images.githubusercontent.com/14130567/77826375-483cfe80-70e5-11ea-965a-f24225cf80ae.png)
