### ISSUE TITLE
EJCW

### ISSUE THREAD

**Issue by Sarigpani** [ShabadOS/database#1411]
| Key | Value |
| --- | ----- |
View | https://database.shabados.com/sources/2/page/155/line/94
Source | Sri Dasam Granth
Page | 155
ID | EJCW
Line | Avrn ky isir dy buirAweI ]

![image](https://user-images.githubusercontent.com/60820452/75612807-0ee19500-5b1f-11ea-8869-a4d12d3583fc.png)

**Comment by bhajneet** [comment]
![image](https://user-images.githubusercontent.com/14130567/77826475-124c4a00-70e6-11ea-83c5-ee034d6596fb.png)
