### ISSUE TITLE
ZDFW

### ISSUE THREAD

**Issue by Sarigpani** [ShabadOS/database#1412]
| Key | Value |
| --- | ----- |
View | https://database.shabados.com/sources/2/page/156/line/1
Source | Sri Dasam Granth
Page | 156
ID | ZDFW
Line | jwn ley jw nwmY qb qy ]5]

![image](https://user-images.githubusercontent.com/60820452/75612834-45b7ab00-5b1f-11ea-80c5-724cedee9aeb.png)

**Comment by bhajneet** [comment]
![image](https://user-images.githubusercontent.com/14130567/77826497-31e37280-70e6-11ea-8c5a-aa4e34ff1dc4.png)
