### ISSUE TITLE
NEZV

### ISSUE THREAD

**Issue by Sarigpani** [ShabadOS/database#1421]
| Key | Value |
| --- | ----- |
View | https://database.shabados.com/sources/2/page/156/line/5
Source | Sri Dasam Granth
Page | 156
ID | NEZV
Line | qw qy nwm ibAMq khwXw ]6]

![image](https://user-images.githubusercontent.com/60820452/75800374-5c554080-5d71-11ea-8f45-912043495a97.png)

**Comment by Sarigpani** [comment]
Forgot to highlight, but add Chaupai after Pauri 6

**Comment by bhajneet** [comment]
Depends on https://github.com/GurbaniNow/gurmukhi-fonts/issues/9
