### ISSUE TITLE
BKKM

### ISSUE THREAD

**Issue by Sarigpani** [ShabadOS/database#1423]
| Key | Value |
| --- | ----- |
View | https://database.shabados.com/sources/2/page/156/line/8
Source | Sri Dasam Granth
Page | 156
ID | BKKM
Line | sB hI jg Brmy BvrwXM ]

![image](https://user-images.githubusercontent.com/60820452/75800584-b3f3ac00-5d71-11ea-9f5d-a13086fee7d3.png)

**Comment by bhajneet** [comment]
Depends on https://github.com/GurbaniNow/gurmukhi-fonts/issues/9
