### ISSUE TITLE
LMDX

### ISSUE THREAD

**Issue by Sarigpani** [ShabadOS/database#1428]
| Key | Value |
| --- | ----- |
View | https://database.shabados.com/sources/2/page/156/line/17
Source | Sri Dasam Granth
Page | 156
ID | LMDX
Line | qw qy sMKÎw sMq sunweI ]9]

![image](https://user-images.githubusercontent.com/60820452/75801088-7b080700-5d72-11ea-90cc-1042d27e8060.png)

**Comment by bhajneet** [comment]
Depends on https://github.com/GurbaniNow/gurmukhi-fonts/issues/9
