### ISSUE TITLE
BNWJ

### ISSUE THREAD

**Issue by Sarigpani** [ShabadOS/database#1432]
| Key | Value |
| --- | ----- |
View | https://database.shabados.com/sources/2/page/156/line/23
Source | Sri Dasam Granth
Page | 156
ID | BNWJ
Line | sMkt hrn nwmu BXo qdw ]

![image](https://user-images.githubusercontent.com/60820452/75801421-071a2e80-5d73-11ea-8941-6050b088d9c9.png)

**Comment by bhajneet** [comment]
Depends on https://github.com/GurbaniNow/gurmukhi-fonts/issues/9
