### ISSUE TITLE
WSHM

### ISSUE THREAD

**Issue by Sarigpani** [ShabadOS/database#1435]
| Key | Value |
| --- | ----- |
View | https://database.shabados.com/sources/2/page/157/line/3
Source | Sri Dasam Granth
Page | 157
ID | WSHM
Line | Xw qy nwmu ibAMq khwXo ]

![image](https://user-images.githubusercontent.com/60820452/75801754-8c054800-5d73-11ea-98ec-fecdb5855719.png)

**Comment by bhajneet** [comment]
Depends on https://github.com/GurbaniNow/gurmukhi-fonts/issues/9
