### ISSUE TITLE
FQVX

### ISSUE THREAD

**Issue by Sarigpani** [ShabadOS/database#1447]
| Key | Value |
| --- | ----- |
View | https://database.shabados.com/sources/2/page/157/line/21
Source | Sri Dasam Granth
Page | 157
ID | FQVX
Line | jwn lXo krqw hm qb qy ]16]

![image](https://user-images.githubusercontent.com/60820452/75803479-5f066480-5d76-11ea-9083-2c51c7e51b5d.png)

**Comment by bhajneet** [comment]
Depends on https://github.com/GurbaniNow/gurmukhi-fonts/issues/9
