### ISSUE TITLE
RBCX

### ISSUE THREAD

**Issue by Sarigpani** [ShabadOS/database#1448]
| Key | Value |
| --- | ----- |
View | https://database.shabados.com/sources/2/page/157/line/24
Source | Sri Dasam Granth
Page | 157
ID | RBCX
Line | jMqR mMqR qMqR n irJwXw ]

![image](https://user-images.githubusercontent.com/60820452/75803542-7f362380-5d76-11ea-8db2-3a0599815727.png)

**Comment by bhajneet** [comment]
Depends on https://github.com/GurbaniNow/gurmukhi-fonts/issues/9
