### ISSUE TITLE
5YV5

### ISSUE THREAD

**Issue by JASJIT123** [shabados/database#146]
> Use the preview tab to see the example given below. Edit the relevant information and preview the changes before submitting. You may delete these instructions.

| Key | Value |
| --- | --- |
| ID | 5YV5 |
| Source | Sri Guru Granth Sahib Ji |
| Page | 2 |
| Line | ```guru eIsru guru gorKu, brmw guru; pwrbqI mweI ]``` |
| Correction | ```THIS``` ≠ ```THAT```  |

PROOF (EDITION)

Jap Ji Sahib Saral Steek by Bhai Joginder Singh Talwara, Bishrams shown in database are incorrect as per Saral Steek.
![image](https://user-images.githubusercontent.com/47263618/52158357-810a5080-2665-11e9-8696-7d2a263afa1f.png)

**Comment by bhajneet** [comment]
Need to finalize daar ji's characters for vishraams
