### ISSUE TITLE
UCYC

### ISSUE THREAD

**Issue by Sarigpani** [ShabadOS/database#1472]
| Key | Value |
| --- | ----- |
View | https://database.shabados.com/sources/2/page/158/line/14
Source | Sri Dasam Granth
Page | 158
ID | UCYC
Line | kwn Cyd jogI khvwXo ]

![image](https://user-images.githubusercontent.com/60820452/75900041-38a6fe80-5e34-11ea-8251-059042fa7d29.png)

**Comment by bhajneet** [comment]
Depends on https://github.com/GurbaniNow/gurmukhi-fonts/issues/9
