### ISSUE TITLE
QNGL

### ISSUE THREAD

**Issue by Sarigpani** [ShabadOS/database#1473]
| Key | Value |
| --- | ----- |
View | https://database.shabados.com/sources/2/page/158/line/15
Source | Sri Dasam Granth
Page | 158
ID | QNGL
Line | Aiq pRpMc kr bnih isDwXo ]

![image](https://user-images.githubusercontent.com/60820452/75900095-507e8280-5e34-11ea-91e1-3538a0aa1eb9.png)

**Comment by bhajneet** [comment]
Depends on https://github.com/GurbaniNow/gurmukhi-fonts/issues/9
