### ISSUE TITLE
ABUV

### ISSUE THREAD

**Issue by Sarigpani** [ShabadOS/database#1478]
| Key | Value |
| --- | ----- |
View | https://database.shabados.com/sources/2/page/158/line/23
Source | Sri Dasam Granth
Page | 158
ID | ABUV
Line | qw qy BXo qyj ibKÎwqw ]

![image](https://user-images.githubusercontent.com/60820452/75900667-28dbea00-5e35-11ea-8ec8-8651b25bab29.png)

**Comment by bhajneet** [comment]
Depends on https://github.com/GurbaniNow/gurmukhi-fonts/issues/9
