### ISSUE TITLE
Add support for multiple sources for each composition

### ISSUE THREAD

**Issue by bhajneet** [ShabadOS/database#1480]
Would require support to have multiple lines for one line in one source. Potentially could require two of our current lines being one line in alternately published source.

All our corrections are being done with published sources. It would be easier to simply make corrections / catalog differences between these sources by looking at the published works.

Our current sources will be "deprecated" as we move to figuring out all lines being from which published sources. Where we know our sources are based on certain publications we can set them now.

Related to https://github.com/ShabadOS/desktop/issues/410 where we will have incomplete published sources.

There will eventually need to be a dragger of sorts allowing for prioritization of these published sources

**Comment by bhajneet** [comment]
@Harjot1Singh need points on this

**Comment by bhajneet** [comment]
_Originally posted in Slack by @Sarabveer_

Currently in Shabad OS: ਨਮੋ ਰਾਜ ਰਾਜੇਸ੍ਵਰੰ ਪਰਮ ਰੂਪੇ ॥੫੦॥
Nihung Santhia: ਨਮੋ ਰਾਜ ਰਾਜੇ ॥ ਸ੍ਵਰੰ ਪਰਮ ਰੂਪੇ ॥੫੦॥

**Comment by bhajneet** [comment]
_Originally posted in Slack by @Harjot1Singh_

```
// previous lines
,{
  id: '21WF',
  gurmukhi: {
      sgpc: 'ਨਮੋ ਰਾਜ ਰਾਜੇਸ੍ਵਰੰ ਪਰਮ ਰੂਪੇ ॥੫੦॥'
      ns: 'ਨਮੋ ਰਾਜ ਰਾਜੇ ॥'
  }
},
{
  id: 'G1GH',
  gurmukhi: {
      ns: ' ਸ੍ਵਰੰ ਪਰਮ ਰੂਪੇ ॥੫੦॥'
     // Notice how SGPC is missing. And that's OK. We won't include the row/data when they use that source.
  }
},
// next lines
```

**Comment by Harjot1Singh** [comment]
We need to adapt DB viewer too btw

**Comment by bhajneet** [comment]
Est difficulty 21
Actual difficulty 5 (3.5)

**Comment by Sarabveer** [comment]
Duplicate #95
