### ISSUE TITLE
YWHB

### ISSUE THREAD

**Issue by UmeetSingh** [ShabadOS/database#150]
> Use the preview tab to see the example given below. Edit the relevant information and preview the changes before submitting. You may delete these instructions.

| Key | Value |
| --- | --- |
| ID | YWHB |
| Source | Vaaran Bhai Gurdas Ji |
| Page | 20 |
| Line | ```gur isK suix gurisK, isKu sdwieAw [``` |
| Correction | ```THIS``` ≠ ```THAT```  |

PROOF (EDITION)

Image:

**Comment by bhajneet** [comment]
![image](https://user-images.githubusercontent.com/14130567/52913120-bda29280-3288-11e9-98ba-195c837cb35c.png)

The issue between the database and the proof is not apparent
