### ISSUE TITLE
XKQZ

### ISSUE THREAD

**Issue by UmeetSingh** [ShabadOS/database#157]
> Use the preview tab to see the example given below. Edit the relevant information and preview the changes before submitting. You may delete these instructions.

| Key | Value |
| --- | --- |
| ID | XKQZ |
| Source | Vaaran Bhai Gurdas Ji |
| Page | 21 |
| Line | ```ihMdU muslmwxu, n scu iswixAw [``` |
| Correction | ```THIS``` ≠ ```THAT```  |

PROOF (EDITION)

Image:

**Comment by bhajneet** [comment]
**Correction:**
iswixAw  ≠ 

**Proof:**
Vaaran Bhai Gurdaas Ji | November 2011 | Shamsher Singh Ashok | SGPC, Sri Amritsar

**Image:**
![image](https://user-images.githubusercontent.com/14130567/52913364-77026780-328b-11e9-981b-d883e2177698.png)
