### ISSUE TITLE
Investigate gur prasad vs gurprasad

### ISSUE THREAD

**Issue by bhajneet** [ShabadOS/database#1572]
List line IDs here which have "gurprasad" without spacing.

**Comment by saihaj** [comment]
These are what I found using the [gurbaniNowAPI](https://api.gurbaninow.com/v2/search/gurpRswid/?source=1&searchtype=4) search:
23WB
3U4G
Y5CM
A0D3
S6YQ
EDM5
FZMM
2JF9
JNW5
46QU
YUND
2JG7
UVC5
170K
361R
3MXZ
FYTG
0UV6
HXUP
12T6

**Comment by bhajneet** [comment]
@saihaj could you actually make a table that outputs the line ID and the corresponding ang in sri guru granth sahib ji? E.g. "XXXX | 140"

This will make proofing against the source much easier

**Comment by saihaj** [comment]
|line_id |pageno |lineno|
|---|---|---|
| 23WB   |81     |15|
| 3U4G   |92     |4 |
| Y5CM   |94     |2 |
| A0D3   |104    |7 |
| S6YQ   |137    |14|
| EDM5   |151    |2 |
| FZMM   |177    |16|
| 2JF9   |186    |15|
| JNW5   |202    |3 |
| 46QU   |211    |17|
| YUND   |220    |18|
| 2JG7   |235    |9 |
| UVC5   |242    |7 |
| 170K   |243    |14|
| 361R   |254    |5 |
| 3MXZ   |259    |18|
| FYTG   |270    |12|
| 0UV6   |270    |15|
| HXUP   |274    |5 |
| 12T6   |277    |17|

**Comment by bhajneet** [comment]
| Key | Value |
| --- | ----- |
View | https://database.shabados.com/sources/1/page/81/line/25
Source | Sri Guru Granth Sahib Ji
Page | 81
ID | 23WB
Line | <> siq nwmu gurpRswid ]

![image](https://user-images.githubusercontent.com/14130567/77862122-6e4ac780-71e7-11ea-82e5-cfb13fa7d990.png)

---

| Key | Value |
| --- | ----- |
View | https://database.shabados.com/sources/1/page/92/line/7
Source | Sri Guru Granth Sahib Ji
Page | 92
ID | 3U4G
Line | gurpRswid; AMqir ilv lwgY ]3]

![image](https://user-images.githubusercontent.com/14130567/77862211-f29d4a80-71e7-11ea-9110-e7b95d46881d.png)

---

| Key | Value |
| --- | ----- |
View | https://database.shabados.com/sources/1/page/94/line/1
Source | Sri Guru Granth Sahib Ji
Page | 94
ID | Y5CM
Line | <> siq nwmu krqw purKu inrBau inrvYru Akwl mUriq AjUnI sYBM gurpRswid ]

![image](https://user-images.githubusercontent.com/14130567/77862243-2d9f7e00-71e8-11ea-9530-ea9fe5f20b5d.png)

---

| Key | Value |
| --- | ----- |
View | https://database.shabados.com/sources/1/page/104/line/16
Source | Sri Guru Granth Sahib Ji
Page | 104
ID | A0D3
Line | ieh miq; gurpRswid min Dwrau ]

![image](https://user-images.githubusercontent.com/14130567/77862307-9850b980-71e8-11ea-8bf2-48257ad61ec9.png)

---

| Key | Value |
| --- | ----- |
View | https://database.shabados.com/sources/1/page/137/line/26
Source | Sri Guru Granth Sahib Ji
Page | 137
ID | S6YQ
Line | <> siq nwmu krqw purKu gurpRswid ]

![image](https://user-images.githubusercontent.com/14130567/77862330-b5858800-71e8-11ea-9bfe-0a091ba2c980.png)

---

| Key | Value |
| --- | ----- |
View | https://database.shabados.com/sources/1/page/151/line/1
Source | Sri Guru Granth Sahib Ji
Page | 151
ID | EDM5
Line | <> siq nwmu krqw purKu inrBau inrvYru Akwl mUriq AjUnI sYBM gurpRswid ]

![image](https://user-images.githubusercontent.com/14130567/77862358-e665bd00-71e8-11ea-9736-1d57366a9d80.png)

---

| Key | Value |
| --- | ----- |
View | https://database.shabados.com/sources/1/page/177/line/45
Source | Sri Guru Granth Sahib Ji
Page | 177
ID | FZMM
Line | gurpRswid; AMimRqu ibKu KwtI ]

![image](https://user-images.githubusercontent.com/14130567/77862386-0eedb700-71e9-11ea-815a-5b44a1f3bc11.png)

---

| Key | Value |
| --- | ----- |
View | https://database.shabados.com/sources/1/page/186/line/43
Source | Sri Guru Granth Sahib Ji
Page | 186
ID | 2JF9
Line | gurpRswid; iknY ivrlY jwnw ]1]

![image](https://user-images.githubusercontent.com/14130567/77862432-4bb9ae00-71e9-11ea-83ba-3c31d45f60aa.png)

---

| Key | Value |
| --- | ----- |
View | https://database.shabados.com/sources/1/page/202/line/8
Source | Sri Guru Granth Sahib Ji
Page | 202
ID | JNW5
Line | gurpRswid; nwnk suK bwsn ]4]110]

![image](https://user-images.githubusercontent.com/14130567/77862445-6c820380-71e9-11ea-823c-b37907cb2514.png)

---

| Key | Value |
| --- | ----- |
View | https://database.shabados.com/sources/1/page/211/line/50
Source | Sri Guru Granth Sahib Ji
Page | 211
ID | 46QU
Line | qUM gurpRswid; kir rwj jogu ]1]

![image](https://user-images.githubusercontent.com/14130567/77862491-a8b56400-71e9-11ea-8dcc-6bd284b53c91.png)
