### ISSUE TITLE
Missing Lines

### ISSUE THREAD

**Issue by bhajneet** [shabados/database#16]
Extended Chaupai Sahib, After Arril, 7555.

**Comment by Harjot1Singh** [comment]
@Sarabveer @bhajneet is this the case with #37?

**Comment by Sarabveer** [comment]
We'll need to follow #71 for this one. Majority of the time, extended Benti Choupai Sahib is read in the Extended Rehraas Sahib, so it can be included in then.

**Comment by Sarabveer** [comment]
Done in #1834
