### ISSUE TITLE
VPMC

### ISSUE THREAD

**Issue by UmeetSingh** [ShabadOS/database#162]
> Use the preview tab to see the example given below. Edit the relevant information and preview the changes before submitting. You may delete these instructions.

| Key | Value |
| --- | --- |
| ID | VPMC |
| Source | Vaaran Bhai Gurdas Ji |
| Page | 22 |
| Line | ```bUMd lK prvwh, hulV vwxIAY [``` |
| Correction | ```THIS``` ≠ ```THAT```  |

PROOF (EDITION)

Image:

**Comment by bhajneet** [comment]
**Correction:**
hulV vwxIAY ≠ hulVvwxIAY

**Proof:**
Vaaran Bhai Gurdaas Ji | November 2011 | Shamsher Singh Ashok | SGPC, Sri Amritsar

**Image:**
![image](https://user-images.githubusercontent.com/14130567/52913461-7f0ed700-328c-11e9-8e29-7dd568fe59c3.png)
