### ISSUE TITLE
FAFR

### ISSUE THREAD

**Issue by kaurharmandeep** [ShabadOS/database#174]
| Key | Value |
| --- | --- |
| ID | FAFR |
| Source | Vaaran Bhai Gurdas Ji |
| Page | 9 |
| Line | ```rqnmwl gurisK jig; gurmiq gux goeI [``` |
| Correction | ```rqnmwl``` ≠ ```rqn mwl```  |

PROOF (EDITION)

Image:
<img width="238" alt="vaaran6" src="https://user-images.githubusercontent.com/31778082/52386444-2e110e80-2a54-11e9-82e4-5cb893edbdf4.PNG">

**Comment by bhajneet** [comment]
Duplicate #173
