### ISSUE TITLE
Shabad translations not lining up (kapal gaae naamai guhi aanee)

### ISSUE THREAD

**Issue by preetcharan** [ShabadOS/database#1757]
shabad: kapal gaae naamai duhi aanee, this whole shabad's translations are messed up against the gurbani, not just this pangti but throughout

https://youtu.be/yaVBZ3OruCk?t=448 - happened in this katha

**Comment by Sarabveer** [comment]
Sometimes, the translation is done for 2 Panktis, in that case, the translation was probably split.

**Comment by Sarabveer** [comment]
![image](https://user-images.githubusercontent.com/4297171/80864481-f68e1380-8c50-11ea-907b-c03a8c16cdc1.png)
![image](https://user-images.githubusercontent.com/4297171/80864489-00b01200-8c51-11ea-946f-7aa608d9b21a.png)

**Comment by Sarabveer** [comment]
@bhajneet what to do in this case? should we strive to keep it as per the source or correctly follow the Gurbani. I am leaning toward the latter.

**Comment by bhajneet** [comment]
These two lines being split could affect English, Spanish, and Punjabi translations. Below is what we have in our DB.

In my opinion if DSSK translations are incorrect, then leave it be. User should use a better translation source if possible. We can also create a derivative translation source where we can change it. So if Basics of Sikhi wants to start an English Translation based on Dr. Sant Singh Khalsa's translation, then we could add a Basics of Sikhi translation which would be more correct on specific lines and fallback to DSSK translation where unprovided by BoS.

@preetcharan as your team does these videos/vichaar perhaps they could also improve the translations to what they believe it should be. If that is agreeable, we'll add a Basics of Sikhi translation to Shabad OS for you to modify.

Does this work @Harjot1Singh @Sarabveer ?

Content | Source
--- | ---
ਦੂਧੁ ਕਟੋਰੈ ਗਡਵੈ ਪਾਨੀ ॥ | Bani
Naam Dayv milked the brown cow, | DSSK
A cup of milk and a jug of water is brought, | BMS
Con agua en el vaso y la copa llena de leche ordeñada de la vaca café, | SN
ਇਕ ਕੌਲ ਦੁਧ ਦਾ ਅਤੇ ਇਕ ਗੜਵਾ ਪਾਣੀ ਦਾ ਲੈ ਆਇਆ, | BMS
ਫਿਰ ਕਟੋਰੇ ਮੇਂ ਦੂਧ ਔਰ ਗਡਵੇ ਮੇਂ ਜਲ ਪਾਇ ਲੀਆ॥ | Fareedkot Teeka
(ਹੇ ਗੋਬਿੰਦ ਰਾਇ! ਤੇਰੇ ਸੇਵਕ ਨਾਮੇ ਨੇ) ਗੜਵੇ ਵਿਚ ਪਾਣੀ ਪਾਇਆ ਹੈ ਤੇ ਕਟੋਰੇ ਵਿਚ ਦੁੱਧ ਪਾਇਆ ਹੈ | Prof. Sahib Singh

Content | Source
--- | ---
ਕਪਲ ਗਾਇ ਨਾਮੈ ਦੁਹਿ ਆਨੀ ॥੧॥ | Bani
And brought a cup of milk and a jug of water to his family god. \|\|1\|\| | DSSK
by Nam Dev, having milked the brown cow. | BMS
fui a ver a mi Dios de piedra. (1) | SN
ਨਾਮਦੇਵ, ਬੂਰੀ ਗਊ ਨੂੰ ਚੋ ਕੇ। | BMS
ਨਾਮਦੇਵ ਜੀ ਨੇ ਠਾਕੁਰ ਜੀ ਕੇ ਭੋਗ ਹੇਤ ਕਪਲਾ ਗਊ (ਦੁਹਿ) ਚੋਇ ਲ੍ਯਾਂਦੀ॥੧॥ | Fareedkot Teeka
ਨਾਮੇ ਨੇ ਗੋਰੀ ਗਾਂ ਚੋ ਕੇ ਲਿਆਂਦੀ ਹੈ ॥੧॥ | Prof. Sahib Singh

Content | Source
--- | ---
ਏਕੁ ਭਗਤੁ ਮੇਰੇ ਹਿਰਦੇ ਬਸੈ ॥ | Bani
The Lord looked upon Naam Dayv and smiled. | DSSK
The saint alone abides within my mind. | BMS
Dios, viendo mi inocencia dijo, | SN
ਕੇਵਲ ਸਾਧੂ ਹੀ ਮੇਰੇ ਚਿੱਤ ਅੰਦਰ ਵਸਦਾ ਹੈ। | BMS
ਤਬ ਬਿਸਨ ਜੀ ਲਛਮੀ ਕੋ ਕਹਤੇ ਹੈਂ: ਏਕ ਭਗਤ ਮੇਰੇ ਮਨੁ ਬੀਚ ਬਸਤਾ ਹੈ, ਮੈਂ ਵਹਾਂ ਜਾਤਾ ਹੂੰ॥ | Fareedkot Teeka
ਮੇਰਾ ਅਨੰਨ ਭਗਤ ਸਦਾ ਮੇਰੇ ਹਿਰਦੇ ਵਿਚ ਵੱਸਦਾ ਹੈ। | Prof. Sahib Singh

Content | Source
--- | ---
ਨਾਮੇ ਦੇਖਿ ਨਰਾਇਨੁ ਹਸੈ ॥੩॥ | Bani
"This one devotee abides within my heart." \|\|3\|\| | DSSK
On seeing Nama, the Lord smiled. | BMS
oh Gurmukj, sé enaltecido en mi corazón. (3) | SN
ਨਾਮੇ ਨੂੰ ਵੇਖ ਕੇ ਸੁਆਮੀ ਹੱਸ ਪਿਆ। | BMS
ਸੋ ਨਾਮਦੇਵ ਜੀ ਕੀ ਦ੍ਰਿੜ ਪ੍ਰੀਤੀ ਦੇਖ ਕੇ ਪ੍ਰਤਖ ਹੋ ਕਰ ਬਿਸਨੂੰ ਜੀ ਹਸਤੇ ਭਏ॥੩॥ | Fareedkot Teeka
ਨਾਮੇ ਨੂੰ ਵੇਖ ਵੇਖ ਕੇ ਪਰਮਾਤਮਾ (ਇਉਂ ਆਖਦਾ ਹੈ ਅਤੇ) ਖ਼ੁਸ਼ ਹੁੰਦਾ ਹੈ ॥੩॥ | Prof. Sahib Singh

**Comment by Sarabveer** [comment]
They aren't incorrect, they just need to be flipped. But that would go against the source.

**Comment by bhajneet** [comment]
What happens when we use https://github.com/ShabadOS/desktop/issues/442 in relation to these translations if they were flipped?

**Comment by Sarabveer** [comment]
Yea, that poses another issue.

**Comment by Sarigpani** [comment]
The translation isn't necessarily incorrect, the splitting has caused the issue as SSK sometimes does one paragraph of translation for 2 lines. The only way to stay true to source would be to present both lines together like SSK has done, but I doubt that is ideal. 
I think its best if we adapt the sentences so they make sense when splitting, even if it requires minor fixing. If you flip the sentences, the grammar won't make sense so you would end up having to edit it anyway.

**Comment by preetcharan** [comment]
i don't mind within the broadcast both pangtia showing if that's possible please

**Comment by bhajneet** [comment]
Closing in favor of #1483 (which will allow BoS to have their own translations based upon any other translation source) and https://github.com/ShabadOS/desktop/issues/442 which will apply to presenters/overlays
