### ISSUE TITLE
Lines not being ordered correctly

### ISSUE THREAD

**Issue by Sarabveer** [ShabadOS/database#1763]
![image](https://user-images.githubusercontent.com/4297171/81484649-3fc40180-9215-11ea-95e9-814d0d7eb063.png)
![image](https://user-images.githubusercontent.com/4297171/81484671-76018100-9215-11ea-80ea-87c2a70249a1.png)

**Comment by Sarabveer** [comment]
https://github.com/GurbaniNow/api/blob/dev/src/v2/routes/page.js#L14

**Comment by Sarabveer** [comment]
Correct (For 2nd Image):
![image](https://user-images.githubusercontent.com/4297171/81484693-b95bef80-9215-11ea-968a-a9b6e9cd73a2.png)

**Comment by Sarabveer** [comment]
I opened up issues to correct these specific errors, but as @Harjot1Singh mentioned, there should be a check implemented for this.

**Comment by bhajneet** [comment]
> Hope this helps, let me know if required more info
<sub>[View in Slack](https://shabados.slack.com/archives/C8LH4UF5H/p1589481250068400)</sub>

**Comment by SSAT** [comment]
Sri Dasam Granth Ji
Issue in json files are
0120.json
0155
0836
1386

Sri Guru Granth Sahib Ji 
Issue in json files are
Issue Pankti Id: CBMX :: Issue on :0006.json
Issue Pankti Id: V17S :: Issue on :0014.json
Issue Pankti Id: E3JV :: Issue on :0014.json
Issue Pankti Id: 493H :: Issue on :0111.json
Issue Pankti Id: E5AQ :: Issue on :0128.json
Issue Pankti Id: HWQK :: Issue on :0144.json
Issue Pankti Id: 3RS6 :: Issue on :0175.json
Issue Pankti Id: RYU3 :: Issue on :0175.json
Issue Pankti Id: ER3Z :: Issue on :0175.json
Issue Pankti Id: 840J :: Issue on :0175.json
Issue Pankti Id: ADHF :: Issue on :0175.json
Issue Pankti Id: 8Z4D :: Issue on :0175.json
Issue Pankti Id: 7JKB :: Issue on :0175.json
Issue Pankti Id: C638 :: Issue on :0175.json
Issue Pankti Id: 1V1P :: Issue on :0175.json
Issue Pankti Id: 2PP7 :: Issue on :0283.json
Issue Pankti Id: Q5H5 :: Issue on :0361.json
Issue Pankti Id: FMRU :: Issue on :0406.json
Issue Pankti Id: 8NYR :: Issue on :0442.json
Issue Pankti Id: 76L5 :: Issue on :0442.json
Issue Pankti Id: GCUC :: Issue on :0442.json
Issue Pankti Id: HVGG :: Issue on :0442.json
Issue Pankti Id: RDAY :: Issue on :0442.json
Issue Pankti Id: FD66 :: Issue on :0442.json
Issue Pankti Id: YT78 :: Issue on :0442.json
Issue Pankti Id: 48RP :: Issue on :0442.json
Issue Pankti Id: Z1Y3 :: Issue on :0442.json
Issue Pankti Id: Z4TY :: Issue on :0442.json
Issue Pankti Id: J05B :: Issue on :0442.json
Issue Pankti Id: RGXR :: Issue on :0478.json
Issue Pankti Id: KXCG :: Issue on :0484.json
Issue Pankti Id: ZGJE :: Issue on :0765.json
Issue Pankti Id: 0CBU :: Issue on :0765.json
Issue Pankti Id: AES3 :: Issue on :0765.json
Issue Pankti Id: 8L0T :: Issue on :0971.json
Issue Pankti Id: YRF9 :: Issue on :0971.json
Issue Pankti Id: W9DY :: Issue on :0971.json
Issue Pankti Id: JXJW :: Issue on :1259.json

**Comment by SSAT** [comment]
@Sarabveer please let me know how you want to proceed with this, Also advise or bug fix branch for this issue.

**Comment by Sarabveer** [comment]
@SSAT I would need to look into how to change the page number without breaking CI builds.

It should be an easy process. For branches, our usual process is to create a new branch off of `dev` and make a Draft PR to track progress.

**Comment by bhajneet** [comment]
It would be preferable to have shorter-living PRs (so no wip/draft PRs for weeks at a time, but one weekend duration is okay), so if need be make the PR smaller so as to complete it earlier. This makes it easier for reviewers too.

Forking is also encouraged and making branches in your personal repos.

See [desktop contributing](https://github.com/ShabadOS/desktop/blob/dev/CONTRIBUTING.adoc#22-branches) for more details

**Comment by bhajneet** [comment]
Depends on fix for #1481 via #1483

**Comment by Sarabveer** [comment]
> 
> 
> Depends on fix for #1481 via #1483

AFAIK this issue isn't dependent on anything. Just page numbers need to be corrected.

**Comment by bhajneet** [comment]
To correct them you're right. You could work on and resolve this issue
today from data perspective. Just need those issues to be resolved in order
to consume correct data.

**Comment by Sarabveer** [comment]
Loads of page number mistakes in Raag Aasa. The iGurbani metadata that was initially imported seems to be problematic.

**Comment by Sarabveer** [comment]
> 
<sub>[View in Slack](https://shabados.slack.com/archives/C8LH4UF5H/p1593142824024800)</sub>
