### ISSUE TITLE
Kahn Singh Nabha dictionary

### ISSUE THREAD

**Issue by skumarudel** [ShabadOS/database#1770]
Dear all,
Thanks a lot for doing such a nice work. I was reading in one of your thread that you already have a database file for Kahn Singh Nabha dictionary..What I am requesting;  is it possible if you could share it with common public. The thing is I read Punjabi books regularly and I sometime find it difficult to look for difficult words. I want to convert the database file to stardict dictionary format, which I can easily install on my laptop. Once its there, I can easily read books and look for words very easily just by highlighting the text. I am talking about http://goldendict.org/dictionaries.php
Thank you in advance... 
Sajan

**Comment by bhajneet** [comment]
Dear Sajan,

Thanks for your request. You may follow the progress at https://github.com/ShabadOS/database/issues/867

Currently we are on hold with this until we can receive a reputable physical copy of Bh. Kahn Singh Nabha's Mahan Kosh.

With covid19, we don't know how long that might take. Once we have a physical copy we will then be able to accurately import the DB.

Again, thank you for your interest!

**Comment by skumarudel** [comment]
Dear, 
I just want to give an update in case it might be useful for you. So what I did, I convert the pdf Mahan kosh into unicode. However, I still need to proof read it. Do you think, I can help you in any way, please let me know. I will be happy to help you as much as I can..I would like to talk on phone if you do not mind to discuss things. If you like, can you send me your cell number on my account @    "skumarudel@gmail.com" .
Thank you,
SK
