### ISSUE TITLE
URWL

### ISSUE THREAD

**Issue by bhajansweet** [shabados/database#1773]
| Key | Value |
| --- | ----- |
View | https://database.shabados.com/line/URWL
Source | Sri Guru Granth Sahib Ji
Page | 795
ID | URWL
Line | eyqy kUk rhau. bygwnw; Baukw. iesu qn qweI ]

Pad chedd according to Shabadaarth Sri Guru Granth Sahib Ji Vol 3, SGPC:

eyqy kUkr hau. bygwnw; Baukw. iesu qn qweI ]

Proof:
![Screenshot_20200526-062917](https://user-images.githubusercontent.com/8877335/82890940-f8c75300-9f1a-11ea-884a-900cb72e855d.png)

**Comment by bhajneet** [comment]
Fixed in #1842
