### ISSUE TITLE
build-json moving subsection key in JSON

### ISSUE THREAD

**Issue by Sarabveer** [ShabadOS/database#1786]
**Describe the bug**
The `build-json` command is moving the subsection key in the json files, which modifies all of the json files.

**To Reproduce**
Run `build-sqlite` and then `build-json`

**Expected behavior**
```
    "id": "CSQ",
    "sttm_id": null,
    "writer": "SGPC",
    "section": "Ardaas",
    "subsection": "Ardaas",
```

**Screenshots**
```
    "id": "CSQ",
    "sttm_id": null,
    "subsection": null,
    "writer": "SGPC",
    "section": "Ardaas",
```

**Comment by saihaj** [comment]
If I log at L124 then the order is the order that is expected but when I log at L125 the order changes for `subsection`

https://github.com/ShabadOS/database/blob/4b8400850237b0bc7cab5e7cecc45b241af8c5a0/lib/build-json.js#L123-L128
