### ISSUE TITLE
5KKA

### ISSUE THREAD

**Issue by saihaj** [shabados/database#1795]
| Key | Value |
| --- | ----- |
View | https://database.shabados.com/line/5KKA
Source | Sri Dasam Granth
Page | 4
ID | 5KKA
Line | nmo rog rogy nmsqM iesnwny ]56]

Screenshot of sources found here https://github.com/ShabadOS/database-viewer#sri-dasam-granth
![E8E93CA6-2CD3-4B1C-A415-061768E2E9B8](https://user-images.githubusercontent.com/44710980/93669013-7711ad00-fa56-11ea-8897-18814ed7cc7b.jpeg)
![C9ED0164-FCAB-4584-9F74-C02A4D144294](https://user-images.githubusercontent.com/44710980/93669014-78db7080-fa56-11ea-85d6-618e7d8a1aa4.jpeg)
![EE10B814-AC67-4089-95F8-B7B8C58E9F1E](https://user-images.githubusercontent.com/44710980/93669015-7a0c9d80-fa56-11ea-8a7b-b548378726aa.jpeg)

**Comment by Sarabveer** [comment]
The `SGPC` source has been corrected as per its proof:

https://github.com/ShabadOS/database/blob/dev/data/Sri%20Dasam%20Granth/0003.json#L2551

**Comment by Sarabveer** [comment]
Closing as already corrected.
