### ISSUE TITLE
Incomplete Shabad

### ISSUE THREAD

**Issue by bhajneet** [shabados/database#1820]
**Describe the bug**

https://viewer.shabados.com/sources/1/page/694/line/4/view

In the wrong section

Could be fixed in new unreleased db

**To Reproduce**

**Expected behavior**

**Screenshots**

**Specs**

**Additional context**

**Comment by Sarabveer** [comment]
Wrong Shabad ID. It should be in previous shabad.

**Comment by bhajneet** [comment]
Can someone write a script to check this? No Shabad would end without numbers on the last line, I'm guessing
