### ISSUE TITLE
how to access dasam granth tex?

### ISSUE THREAD

**Issue by tensorfoo** [shabados/database#1830]
i'd like to get the unicode text but i haven't come across where it is available via API. Any pointers appreciated!

**Comment by saihaj** [comment]
Hello 👋🏼 

Rest API checkout Gurbani Now it uses ShabadOS database https://github.com/GurbaniNow/api/wiki/API-Documentation
Looking for utilities to convert ascii to unicode checkout https://docs.shabados.com/gurmukhi-utils

You can also join our slack https://chat.shabados.com/

**Comment by tensorfoo** [comment]
Thank you!

**Comment by bhajneet** [comment]
This question reminds me that we should probably link to the docs in the readme

https://docs.shabados.com/database/installing-or-accessing#gurbaninow-rest-api
