### ISSUE TITLE
Word does not match source ( pairi yayya ), maybe font issue

### ISSUE THREAD

**Issue by cingh-jasdeep** [shabados/database#1887]
### Describe the bug

WJKK WJKF ji

I was going through Shabads in Amrit Keertan 
found that this word does not match the source

https://viewer.shabados.com/sources/1/page/1386/line/32
![Screenshot 2023-06-27 at 12 13 44 PM](https://github.com/shabados/database/assets/5167015/8da05d3d-cdc6-4678-b503-a5a1e00b91ee)

https://commons.wikimedia.org/w/index.php?title=File%3AGuru_Granth_Sahib_Part_Two.pdf&page=672
![Screenshot 2023-06-27 at 12 16 50 PM](https://github.com/shabados/database/assets/5167015/e071d54b-ba24-4170-8453-f4e23cd5e5df)

### Environment

MacOS 10.15.7,  Chrome 114

**Comment by bhajneet** [comment]
That is the same character, yakash U+0A75

Different fonts show it with different styles, but it is the same
