### ISSUE TITLE
English translations not matching with Text in Ghazals Bhai Nand Lal Ji

### ISSUE THREAD

**Issue by cingh-jasdeep** [ShabadOS/database#1892]
### Describe the bug

![Screenshot 2023-07-12 at 3 56 23 PM](https://github.com/ShabadOS/database/assets/5167015/4b7f9c71-e71b-40fd-b562-bdcef26f54f6)
![Screenshot 2023-07-12 at 3 58 33 PM](https://github.com/ShabadOS/database/assets/5167015/fcd117c3-86b5-4e59-ab86-d5b8a916e596)

**Comment by bhajneet** [comment]
Having trouble locating these lines in the following source:

```
Kalaam-e-Goya. Translated by Pritpal S Bindra, Institute of Sikh Studies, Chandigarh, 2003
```

Looks like we'll have to redo it more properly at some point.

**Comment by sarabveer** [comment]
Duplicate #1327
