### ISSUE TITLE
Multiple lines combined into 1 line

### ISSUE THREAD

**Issue by cingh-jasdeep** [ShabadOS/database#1893]
### Describe the bug

In some places, multiple lines are combined into 1 line
![Screenshot 2023-07-15 at 11 11 41 AM](https://github.com/ShabadOS/database/assets/5167015/985b7a12-e92f-4466-b45a-87e3f80fe910)

**Comment by sarabveer** [comment]
This shabad is a tipada, which each pada being an iktuka. Some older manuscripts have been observed not to have the double-dandi in the line, but it has been kept to maintain parity with current print edition. You will note that the 2 shabads before that, and the one shabad after have the same.

<img width="657" alt="image" src="https://github.com/ShabadOS/database/assets/4297171/6282f3f5-28a8-439d-91d6-c195b78bdb53">
