### ISSUE TITLE
There is one problem in gurbani now api. ਬੰਨੑਾ  in japji sahib. correct is ਬੰਨਾ

### ISSUE THREAD

**Issue by 1041harpreet** [shabados/database#1896]
### Describe the bug

waheguru g ka khalsa waheguru g ki fateh. there is one problem in gurbani now api. ਬੰਨੑਾ  in japji sahib. i have shared some images , check this api https://api.gurbaninow.com/v2/banis/1 , and check correct images also. check incorrect and correct images and update on server.
![WhatsApp Image 2023-10-30 at 3 36 12 PM](https://github.com/shabados/database/assets/96649743/19725d93-fb23-4d64-af10-e9390700fd13)
![WhatsApp Image 2023-10-30 at 3 36 10 PM](https://github.com/shabados/database/assets/96649743/637a78f6-3909-47a9-bee8-5d27688760ab)
![WhatsApp Image 2023-10-30 at 3 36 11 PM (2)](https://github.com/shabados/database/assets/96649743/d9c0c173-ce6e-49de-abed-1fd995dc31d4)
![WhatsApp Image 2023-10-30 at 3 36 11 PM (1)](https://github.com/shabados/database/assets/96649743/4191c42b-c8ed-4cd8-b54f-adb6863e1f6f)

**Comment by bhajneet** [comment]
Hello ji, thank you for opening this issue. The Shabad OS Database line you're referring to is here:

https://github.com/shabados/database/blob/next/data/Sri%20Guru%20Granth%20Sahib%20Ji/0001.json#L305C36-L305C36

It is set to "jy bMnw purIAw Bwr" which in Unicode is "ਜੇ ਬੰਨਾ ਪੁਰੀਆ ਭਾਰ".

The link you're checking is by GurbaniNow. They used to use Shabad OS in the past, but it seems they've gone their own way the past year (without notifying us). Sorry for any confusion.

For better follow up, I recommend you message @sarabveer or contact the GurbaniNow team from their website: https://gurbaninow.com/about
