### ISSUE TITLE
DFGW

### ISSUE THREAD

**Issue by kaurharmandeep** [ShabadOS/database#191]
| Key | Value |
| --- | --- |
| ID | DFGW |
| Source | Vaaran Bhai Gurdas Ji |
| Page | 10 |
| Line | ```Gir AweI Twkur imly; pYj rhI boly srmWdI [``` |
| Correction | ```srmWdI ``` ≠ ```SrmWdI ```  |

PROOF (EDITION)

Image:
<img width="389" alt="vaaran17" src="https://user-images.githubusercontent.com/31778082/52507345-42bde580-2bbf-11e9-8ceb-bd0f1fc9948b.PNG">

**Comment by Sarabveer** [comment]
`srmWdI` should stay the same.

Though `SrmWdI` is correct pronunciation.

**Comment by bhajneet** [comment]
Master branch shows this line as `srmWdI`

https://github.com/ShabadOS/database/blob/master/data/Vaaran%20Bhai%20Gurdas%20Ji/10.json#L1893

**Comment by bhajneet** [comment]
#375
