### ISSUE TITLE
Inconsistent Unicode Fonts

### ISSUE THREAD

**Issue by bhajansweet** [ShabadOS/database#23]
Not sure if this should be an "issue," but we should be careful with the unicode font we decide to use as some accent marks are displayed differently in different fonts. For example, on GuruGranthDarpan.net, the font they use requires them to write "ਕਲ੍ਯ੍ਯ" where other fonts would simply write it "ਕਲ੍ਯ" (http://www.gurugranthdarpan.net/1392.html).

**Comment by Harjot1Singh** [comment]
The latter is more correct, right? We should definitely not use any fonts that change the representation required for storing the data.
