### ISSUE TITLE
SHNY

### ISSUE THREAD

**Issue by kaurharmandeep** [ShabadOS/database#261]
| Key | Value |
| --- | --- |
| ID | SHNY |
| Source | Vaaran Bhai Gurdas Ji |
| Page | 12 |
| Line | ```lK lK cMd crwgcI; lK lK AMimRq pIcin Joly [``` |
| Correction | ```crwgcI``` ≠ ```crwZcI```  |

PROOF (EDITION)

Image:
<img width="360" alt="vaaran53" src="https://user-images.githubusercontent.com/31778082/52527723-63f40400-2c9b-11e9-9509-d6d0f10ac5c4.PNG">

**Comment by Sarabveer** [comment]
This should not be merged, keep as `crwgcI` and add `crwZcI` to notes.

Depends on #375

**Comment by bhajneet** [comment]
Didn't notice your note. Cancelled PR.
