### ISSUE TITLE
0NVY

### ISSUE THREAD

**Issue by HarminderSingh** [ShabadOS/database#275]
> Use the preview tab to see the example given below. Edit the relevant information and preview the changes before submitting. You may delete these instructions.

| Key | Value |
| --- | --- |
| ID | 0NVY |
| Source | Sri Guru Granth Sahib Ji |
| Page | 1 |
| Line | ```<> siq nwmu krqw purKu inrBau inrvYru; Akwl mUriq AjUnI sYBM gurpRswid ]``` |
| Correction | ```gurpRswid``` ≠ ```gur pRswid```  |

PROOF (EDITION)
all sgpc is correct
Image:

**Comment by HarminderSingh** [comment]
@Sarabveer see dis just one example, not gud. dis on moolmantr

**Comment by bhajneet** [comment]
**Correction:**
gurpRswid ≠ gur pRswid

**Proof:**
Sri Guru Granth Sahib (Unicode) | SGPC.net

**Image:**
![image](https://user-images.githubusercontent.com/14130567/52913808-7c61b100-328f-11e9-8a44-160e019c9394.png)
