### ISSUE TITLE
Include `॥` in `first_letters`

### ISSUE THREAD

**Issue by Harjot1Singh** [ShabadOS/database#31]
Searches leak over to next line when using the `LIKE` operator, so should probably include `॥` when generating `first_letters`.

Running `SELECT * FROM lines WHERE first_letters LIKE 'ਸਕਨਨਅ'` will return `ਅਰਜਨ ਸਿੰਘ ਅਰੁ ਅਮਿਟ ਸਿੰਘ ਕ੍ਰਿਸ਼ਨ ਨਿਹਾਰਓ ਨੈਨ ॥ ਅਾਠ ਭੂਪ ਮਿਲਿ ਪਰਸਪਰ ਬੋਲਤ ਅੈਸੇ ਬੈਨ ॥੧੧੮੩॥`.

**Comment by Harjot1Singh** [comment]
This is also really a symptom of having multiple lines per row in some cases in the DB.

**Comment by Harjot1Singh** [comment]
Should be no longer required, as multi-line lines should be fixed in #37.

**Comment by bhajneet** [comment]
This conflicts with first letter ordering (full line match at top). If there is a bug of characters overflowing, that should be a separate issue.
