### ISSUE TITLE
EAPA

### ISSUE THREAD

**Issue by UmeetSingh** [ShabadOS/database#312]
> Use the preview tab to see the example given below. Edit the relevant information and preview the changes before submitting. You may delete these instructions.

| Key | Value |
| --- | --- |
| ID | EAPA |
| Source | Vaaran Bhai Gurdas Ji |
| Page | 24 |
| Line | ```inhcl nIau DrweIEnu; swDsMgiq scKMf smyau [``` |
| Correction | ```THIS``` ≠ ```THAT```  |

PROOF (EDITION)

Image:

**Comment by bhajneet** [comment]
**Correction:**
scKMf ≠ sc KMf

**Proof:**
Vaaran Bhai Gurdaas Ji | November 2011 | Shamsher Singh Ashok | SGPC, Sri Amritsar

**Image:**
![image](https://user-images.githubusercontent.com/14130567/53605979-22ae9000-3b87-11e9-8958-5100380c7b04.png)
