### ISSUE TITLE
VQKV

### ISSUE THREAD

**Issue by UmeetSingh** [ShabadOS/database#315]
> Use the preview tab to see the example given below. Edit the relevant information and preview the changes before submitting. You may delete these instructions.

| Key | Value |
| --- | --- |
| ID | VQKV |
| Source | Vaaran Bhai Gurdas Ji |
| Page | 24 |
| Line | ```shj srovir prmhMsu; gurmiq moqI mwxk cogI [``` |
| Correction | ```THIS``` ≠ ```THAT```  |

PROOF (EDITION)

Image:

**Comment by bhajneet** [comment]
**Correction:**
prmhMsu ≠ prm hMsu

**Proof:**
Vaaran Bhai Gurdaas Ji | November 2011 | Shamsher Singh Ashok | SGPC, Sri Amritsar

**Image:**
![image](https://user-images.githubusercontent.com/14130567/53606138-b3856b80-3b87-11e9-8ffb-ed693ec33662.png)
