### ISSUE TITLE
LVWC

### ISSUE THREAD

**Issue by UmeetSingh** [ShabadOS/database#318]
> Use the preview tab to see the example given below. Edit the relevant information and preview the changes before submitting. You may delete these instructions.

| Key | Value |
| --- | --- |
| ID | LVWC |
| Source | Vaaran Bhai Gurdas Ji |
| Page | 24 |
| Line | ```vyd kqyb Agocrw; gurmuiK sbdu swD sMgu sqw [``` |
| Correction | ```THIS``` ≠ ```THAT```  |

PROOF (EDITION)

Image:

**Comment by bhajneet** [comment]
**Correction:**
swD sMgu ≠ swDsMgu

**Proof:**
Vaaran Bhai Gurdaas Ji | November 2011 | Shamsher Singh Ashok | SGPC, Sri Amritsar

**Image:**
![image](https://user-images.githubusercontent.com/14130567/53606364-98ffc200-3b88-11e9-953a-386211f8b668.png)
