### ISSUE TITLE
ZFZC

### ISSUE THREAD

**Issue by UmeetSingh** [ShabadOS/database#320]
> Use the preview tab to see the example given below. Edit the relevant information and preview the changes before submitting. You may delete these instructions.

| Key | Value |
| --- | --- |
| ID | ZFZC |
| Source | Vaaran Bhai Gurdas Ji |
| Page | 24 |
| Line | ```gurprcY gur jwxIAY; igAwin iDAwin ismrix gurbwxI [``` |
| Correction | ```THIS``` ≠ ```THAT```  |

PROOF (EDITION)

Image:

**Comment by bhajneet** [comment]
**Correction:**
gurprcY ≠ gur prcY

**Proof:**
Vaaran Bhai Gurdaas Ji | November 2011 | Shamsher Singh Ashok | SGPC, Sri Amritsar

**Image:**
![image](https://user-images.githubusercontent.com/14130567/53606475-f09e2d80-3b88-11e9-9b3f-0c180adf4c93.png)
