### ISSUE TITLE
PSDK

### ISSUE THREAD

**Issue by UmeetSingh** [ShabadOS/database#321]
> Use the preview tab to see the example given below. Edit the relevant information and preview the changes before submitting. You may delete these instructions.

| Key | Value |
| --- | --- |
| ID | PSDK |
| Source | Vaaran Bhai Gurdas Ji |
| Page | 24 |
| Line | ```pYrI pY pwKwk hoie; grbu invwir grIbI AwxI [``` |
| Correction | ```THIS``` ≠ ```THAT```  |

PROOF (EDITION)

Image:

**Comment by bhajneet** [comment]
**Correction:**
pwKwk ≠ pw Kwk

**Proof:**
Vaaran Bhai Gurdaas Ji | November 2011 | Shamsher Singh Ashok | SGPC, Sri Amritsar

**Image:**
![image](https://user-images.githubusercontent.com/14130567/53606507-10355600-3b89-11e9-8c78-10ee126ef31a.png)
