### ISSUE TITLE
ZNVB

### ISSUE THREAD

**Issue by kaurharmandeep** [ShabadOS/database#458]
| Key | Value |
| --- | --- |
| ID | ZNVB |
| Source | Vaaran Bhai Gurdas Ji |
| Page | 17 |
| Line | ```sBy hI ptrwxIAw; rwjy iekdU iek ipAwrI [``` |
| Correction | ```iekdU``` ≠ ```iek dU```  |
| OR|
| Correction | ```iekdU``` ≠ ```iekdUM```  |

PROOF (EDITION)
Image:
<img width="395" alt="vaaran87" src="https://user-images.githubusercontent.com/31778082/53135270-9a0d6f80-3548-11e9-99e1-e3223e8a1bb7.PNG">

OR

![capture 4](https://user-images.githubusercontent.com/31778082/53135636-ff159500-3549-11e9-9d7a-3c55a1fe64c0.jpeg)

**Comment by bhajneet** [comment]
@Sarabveer `iek dU` vs `iekdUM`

**Comment by Sarabveer** [comment]
`iek dU`
