### ISSUE TITLE
Wrong author of shabad (jo nar dukh mai dukh nehee manai)

### ISSUE THREAD

**Issue by preetcharan** [ShabadOS/database#46]
jo nru duK mY duKu nhI mwnY ]
jo nar dhukh mai dhukh nehee maanai ||

This shabad on ang 633 is showing that the author is Bhagat Bhikhan Ji. This shabad is written by M9.

Source - the title of the shabad says sorath mehalaa 9

**Comment by Harjot1Singh** [comment]
Can @Sarabveer or @bhajneet pick this up please :)

**Comment by Sarabveer** [comment]
https://github.com/ShabadOS/database/blob/723f28533062a04acd4373fab320a803958bc113/data/Sri%20Guru%20Granth%20Sahib%20Ji/0633.json#L1231

Looks like it is fine in the New Database, maybe problem with old one?

**Comment by Harjot1Singh** [comment]
Sounds like you’re right. Fixed in #37.
