### ISSUE TITLE
'?' in between shabad

### ISSUE THREAD

**Issue by SukhmanpreetSingh** [ShabadOS/database#47]
![img-20180712-wa0000](https://user-images.githubusercontent.com/33250386/42606896-88f948f0-859d-11e8-910e-b80c907313e3.jpg)

**Comment by bhajneet** [comment]
This is in new db

@sarabveer

**Comment by Sarabveer** [comment]
No, this is only an issue with the old database.

**Comment by bhajneet** [comment]
So interestingly this is in the second search result in old db (amrit kirtan). In semi-merged db it becomes the first search result. However, confirmed that this is an issue with old database's amrit kirtan results. Neither has the issue outside amrit kirtan.

**Comment by Sarabveer** [comment]
Whoever supplied the old Database didn't know how to handle codepages/encodings properly.

This is/was also an issue with iGurbani and their database.
