### ISSUE TITLE
ARAG

### ISSUE THREAD

**Issue by UmeetSingh** [ShabadOS/database#530]
> Use the preview tab to see the example given below. Edit the relevant information and preview the changes before submitting. You may delete these instructions.

| Key | Value |
| --- | --- |
| ID | ARAG |
| Source | Vaaran Bhai Gurdas Ji |
| Page | 25 |
| Line | bil poqw pRihlwd dw; ieMdr purI dI ieC ieCMdw [ |
| Correction | THIS ≠ THAT  |

PROOF (EDITION)

Image:

**Comment by bhajneet** [comment]
**Correction:**
ieMdr purI ≠ ieMdrpurI

**Proof:**
Vaaran Bhai Gurdaas Ji | November 2011 | Shamsher Singh Ashok | SGPC, Sri Amritsar

**Image:**
![image](https://user-images.githubusercontent.com/14130567/53913990-9854a900-402a-11e9-93f3-7599396eb19e.png)
