### ISSUE TITLE
6160

### ISSUE THREAD

**Issue by UmeetSingh** [ShabadOS/database#538]
> Use the preview tab to see the example given below. Edit the relevant information and preview the changes before submitting. You may delete these instructions.

| Key | Value |
| --- | --- |
| ID | 6160 |
| Source | Vaaran Bhai Gurdas Ji |
| Page | 25 |
| Line | sbd suriq ilvlIxu hoie; inrMkwr scKMif invwsI [ |
| Correction | THIS ≠ THAT  |

PROOF (EDITION)

Image:

**Comment by bhajneet** [comment]
**Correction:**
ilvlIxu ≠ ilv lIxu
scKMif ≠ sc KMif

**Proof:**
Vaaran Bhai Gurdaas Ji | November 2011 | Shamsher Singh Ashok | SGPC, Sri Amritsar

**Image:**
![image](https://user-images.githubusercontent.com/14130567/53914553-d6060180-402b-11e9-902c-d5ffbfa47004.png)
