### ISSUE TITLE
GGLJ

### ISSUE THREAD

**Issue by UmeetSingh** [ShabadOS/database#539]
> Use the preview tab to see the example given below. Edit the relevant information and preview the changes before submitting. You may delete these instructions.

| Key | Value |
| --- | --- |
| ID | GGLJ |
| Source | Vaaran Bhai Gurdas Ji |
| Page | 26 |
| Line | scY qKiq invwsu hY; swDsMgiq scKMif vsMdw [ |
| Correction | THIS ≠ THAT  |

PROOF (EDITION)

Image:

**Comment by bhajneet** [comment]
**Correction:**
scKMif ≠ sc KMif

**Proof:**
Vaaran Bhai Gurdaas Ji | November 2011 | Shamsher Singh Ashok | SGPC, Sri Amritsar

**Image:**
![image](https://user-images.githubusercontent.com/14130567/53914603-03eb4600-402c-11e9-93ad-51820002cdee.png)
