### ISSUE TITLE
DMAC

### ISSUE THREAD

**Issue by UmeetSingh** [ShabadOS/database#574]
> Use the preview tab to see the example given below. Edit the relevant information and preview the changes before submitting. You may delete these instructions.

| Key | Value |
| --- | --- |
| ID | DMAC |
| Source | Vaaran Bhai Gurdas Ji |
| Page | 27 |
| Line | icru jIvxu bhu hMFxw, gux igAwn augwhI [ |
| Correction | THIS ≠ THAT  |

PROOF (EDITION)

Image:

**Comment by bhajneet** [comment]
**Correction:**
icru jIvxu ≠ icrujIvxu

**Proof:**
Vaaran Bhai Gurdaas Ji | November 2011 | Shamsher Singh Ashok | SGPC, Sri Amritsar

**Image:**
![image](https://user-images.githubusercontent.com/14130567/54086841-b4ef2a80-4323-11e9-86c7-e0da6c6d46bf.png)
