### ISSUE TITLE
KQTD

### ISSUE THREAD

**Issue by UmeetSingh** [ShabadOS/database#578]
> Use the preview tab to see the example given below. Edit the relevant information and preview the changes before submitting. You may delete these instructions.

| Key | Value |
| --- | --- |
| ID | KQTD |
| Source | Vaaran Bhai Gurdas Ji |
| Page | 28 |
| Line | gur isKI dw ilKxw; lK n icqR gupiq iliK jwxY [ |
| Correction | THIS ≠ THAT  |

PROOF (EDITION)

Image:

**Comment by bhajneet** [comment]
**Correction:**
gur isKI ≠ gurisKI

**Proof:**
Vaaran Bhai Gurdaas Ji | November 2011 | Shamsher Singh Ashok | SGPC, Sri Amritsar

**Image:**
![image](https://user-images.githubusercontent.com/14130567/54086923-786ffe80-4324-11e9-9e37-53030d11e694.png)
