### ISSUE TITLE
Remove SnakeCase conversion?

### ISSUE THREAD

**Issue by Harjot1Singh** [ShabadOS/database#58]
Currently all snake_case fields in DB are outputted as camelCase when using the API.

Unsure if this is confusing. @bhajneet @Sarabveer, any input?

Either remove, or improve consistency by using knex mapper instead.

**Comment by bhajneet** [comment]
Keep it simple for API users by giving them clear documentation. Doesn't matter what you choose in end -- it's fine either way. Can add knex mapper in future if you want.

**Comment by Harjot1Singh** [comment]
Issue is that schema is obviously designed and documented using `snake_case`, but there is a note in the docs about the JS API using `camelCase`.

Instead, I think it might be better to return `snake_case` by default, but add a chainable `.toCamelCase()` method so it's an opt-in feature instead.

**Comment by Harjot1Singh** [comment]
Going to apply knex case mappers instead, so that all operations using the JS API will use camelCase, to avoid confusion

**Comment by Harjot1Singh** [comment]
Apparently not. Results will be automatically mapped to camelCase, but querying fields will still require snake_case.
