### ISSUE TITLE
HKKD

### ISSUE THREAD

**Issue by UmeetSingh** [ShabadOS/database#582]
> Use the preview tab to see the example given below. Edit the relevant information and preview the changes before submitting. You may delete these instructions.

| Key | Value |
| --- | --- |
| ID | HKKD |
| Source | Vaaran Bhai Gurdas Ji |
| Page | 28 |
| Line | gur isKI dw isKxw; gurmuiK swDsMgiq dI syvw [ |
| Correction | THIS ≠ THAT  |

PROOF (EDITION)

Image:

**Comment by bhajneet** [comment]
**Correction:**
gur isKI ≠ gurisKI

**Proof:**
Vaaran Bhai Gurdaas Ji | November 2011 | Shamsher Singh Ashok | SGPC, Sri Amritsar

**Image:**
![image](https://user-images.githubusercontent.com/14130567/54087054-aa359500-4325-11e9-8860-cc36b8a61e79.png)
