### ISSUE TITLE
CVQU

### ISSUE THREAD

**Issue by UmeetSingh** [ShabadOS/database#590]
> Use the preview tab to see the example given below. Edit the relevant information and preview the changes before submitting. You may delete these instructions.

| Key | Value |
| --- | --- |
| ID | CVQU |
| Source | Vaaran Bhai Gurdas Ji |
| Page | 28 |
| Line | gur isKI dw rwhu eyhu; gurmuiK cwl clY so dyKY [ |
| Correction | THIS ≠ THAT  |

PROOF (EDITION)

Image:

**Comment by bhajneet** [comment]
**Correction:**
gur isKI ≠ guris`KI

**Proof:**
Vaaran Bhai Gurdaas Ji | November 2011 | Shamsher Singh Ashok | SGPC, Sri Amritsar

**Image:**
![image](https://user-images.githubusercontent.com/14130567/54087132-71e28680-4326-11e9-8a7c-1c9f750f4376.png)
