### ISSUE TITLE
BDBU

### ISSUE THREAD

**Issue by UmeetSingh** [ShabadOS/database#593]
> Use the preview tab to see the example given below. Edit the relevant information and preview the changes before submitting. You may delete these instructions.

| Key | Value |
| --- | --- |
| ID | BDBU |
| Source | Vaaran Bhai Gurdas Ji |
| Page | 28 |
| Line | gur isKI dw qolxw; quil n qoil qulY qul Dwrw [ |
| Correction | THIS ≠ THAT  |

PROOF (EDITION)

Image:

**Comment by bhajneet** [comment]
**Correction:**
gur isKI ≠ gurisKI
qul Dwrw ≠ qulDwrw

**Proof:**
Vaaran Bhai Gurdaas Ji | November 2011 | Shamsher Singh Ashok | SGPC, Sri Amritsar

**Image:**
![image](https://user-images.githubusercontent.com/14130567/54087330-2fba4480-4328-11e9-90b2-75fd8fb9ddde.png)
