### ISSUE TITLE
QNZM

### ISSUE THREAD

**Issue by UmeetSingh** [ShabadOS/database#612]
> Use the preview tab to see the example given below. Edit the relevant information and preview the changes before submitting. You may delete these instructions.

| Key | Value |
| --- | --- |
| ID | QNZM |
| Source | Vaaran Bhai Gurdas Ji |
| Page | 28 |
| Line | gur isKI dw krmu eyhu; gur Purmwey gurisK krxw [ |
| Correction | THIS ≠ THAT  |

PROOF (EDITION)

Image:

**Comment by bhajneet** [comment]
I don't see the issue here:

**Image:**
![image](https://user-images.githubusercontent.com/14130567/54087330-2fba4480-4328-11e9-90b2-75fd8fb9ddde.png)

**Comment by bhajneet** [comment]
@Sarabveer can you please confirm with more research? It's the only one that doesn't follow the rest of the page.

**Comment by Sarabveer** [comment]
![image](https://i.imgur.com/FM6Hseb.png)

**Comment by Sarabveer** [comment]
@bhajneet it should be put together
