### ISSUE TITLE
Schema.js

### ISSUE THREAD

**Issue by HsinghN** [ShabadOS/database#682]
table.integer( 'section_id' ).references( 'id' ).inTable( 'section' )

('section') or ('sectionS')

**Comment by Harjot1Singh** [comment]
WJKK WJKF, thanks for looking at the project, good catch! Feel free to put in a PR :)

**Comment by HsinghN** [comment]
WGJKK WGJKF, I don't know what PR means.

**Comment by Harjot1Singh** [comment]
Sorry Veerji, a pull request, whereby you can implement the correction and we can accept it into the branch.

Also, if you wish to get involved in the project, or want to discuss anything with us, feel free to join us at https://chat.shabados.com
