### ISSUE TITLE
XNAS

### ISSUE THREAD

**Issue by Sarabveer** [ShabadOS/database#713]
> Use the preview tab to see the example given below. Edit the relevant information and preview the changes before submitting. You may delete these instructions.

| Key | Value |
| --- | --- |
| ID | XNAS |
| Source | Sri Guru Granth Sahib Ji |
| Page | 305 |
| Line | quDu jyvfu. mY horu ko idis, nw AwveI; qUhYN suGVu. myrY min Bwxw ] |
| Correction | nw ≠ n  |
| Correction | qUhYN ≠ qU hYN  |

Shabadarth, Volume 1, SGPC
Image:
![image](https://user-images.githubusercontent.com/4297171/56775269-4a3f6480-6794-11e9-97e1-6d0415f2f5f0.png)

**Comment by bhajneet** [comment]
I've updated to note the split `qUhYN`. Please confirm which bindi ASCII char to use.

**Comment by Sarabveer** [comment]
I don't think its right, SGPC.net PDF has it the way it is currently.
![image](https://user-images.githubusercontent.com/4297171/56776402-2ed75800-679a-11e9-933c-3c909bde343d.png)
