### ISSUE TITLE
BRGB

### ISSUE THREAD

**Issue by kaurharmandeep** [ShabadOS/database#726]
| Key | Value |
| --- | --- |
| ID | BRGB |
| Source | Vaaran Bhai Gurdas Ji |
| Page | 37 |
| Line | mnmuK AMnHy rwiq idhuM; suriq ivhUxy ckI Joˆdy [ |
| Correction | idhuM ≠ idhuN |

PROOF (EDITION)

Image:
<img width="455" alt="Vaaran151" src="https://user-images.githubusercontent.com/31778082/57187373-89b83000-6ebb-11e9-9874-fc9f83028fa5.PNG">

**Comment by bhajneet** [comment]
@Harjot1Singh / @Sarabveer there should be a check for `oˆ`, they should be autoconverted to `oN`

**Comment by Sarabveer** [comment]
This one should be `oˆ` not `oN`

**Comment by bhajneet** [comment]
The highlighted one should be `uˆ` as committed in fix-BRGB.

Please note the last word in our JSON file, it should not be `oˆ`. Pretty sure any scenario with `oˆ` should be `oN` for readability.

**Comment by Sarabveer** [comment]
Yea, it should be `uˆ` for the highlighted one and `oN` for the last word. I looked at the wrong one.
