### ISSUE TITLE
Shabad 4WQ - Gurbani Dian Laga Matra Di Vilakhanta

### ISSUE THREAD

**Issue by Sarabveer** [shabados/database#84]
| Key | Value |
| ---- | ------ |
| ShabadID | 4WQ |
| Shabad OS  | `iq nr duK nh BuK; iq nr inDn, nhu khIAih ]`<br> `iq nr soku, nhu huAY; iq nr sy AMqu, n lhIAih ]`<br> `iq nr syv. nhu krih; iq nr. sX shs smpih ]`<br> `iq nr dulIcY bhih; iq nr auQip ibQpih ]`<br> `suK lhih. iq nr sMswr mih; ABY ptu, irp miD iqh ]`<br> `skXQ iq nr. jwlpu BxY; gur Amrdwsu supRsMnu ijh ]2]11]` |
| Gurbani Dian Laga Matra Di Vilakhanta  |  `iq nr` ≠ `iqnr`  |
 
Gurbani Dian Laga Matra Di Vilakhanta (3rd Edition,  November 2003)  
Page 343  
![](https://i.imgur.com/aJQ0nBu.jpg)

Page 344  
![](https://i.imgur.com/yv8ATua.jpg)

Page 345  
![](https://i.imgur.com/SZIaDfP.jpg)

**Comment by bhajneet** [comment]
Page on [Guru Granth Darpan](http://www.gurugranthdarpan.net/1394.html)

![image](https://user-images.githubusercontent.com/14130567/50060198-c7abf600-015e-11e9-9aad-ca1835710fb1.png)

**Comment by Sarabveer** [comment]
ਜੋਗਿੰਦਰ ਸਿੰਘ ਤਲਵਾੜਾ, ਭੱਟਾ ਦੇ ਸਵਈਏ ਸਟੀਕ

![](https://i.imgur.com/zFKCY4V.jpg)

![](https://i.imgur.com/P87ciRx.jpg)

![](https://i.imgur.com/Pv1KIvp.jpg)

**Comment by Sarabveer** [comment]
According to SGPC Shabad Arth Pothi from 2003, it should be `iqnr`

![image](https://user-images.githubusercontent.com/4297171/50719383-406ce680-1069-11e9-9a42-61a038f5f37d.png)

**Comment by Sarabveer** [comment]
Depends on #95

**Comment by bhajneet** [comment]
Depends on #1480
