### ISSUE TITLE
AFCF - Gurbani Dian Laga Matra Di Vilakhanta

### ISSUE THREAD

**Issue by Sarabveer** [shabados/database#85]
| Key | Value |
| ---- | ------ |
| ID | AFCF |
| Shabad OS  | `siqguru pRmwxu, ibD nY isirau; jig. js qUru bjwieAau ]`  |
| Gurbani Dian Laga Matra Di Vilakhanta  |  `ibD nY` ≠ `ibDnY`  |

Gurbani Dian Laga Matra Di Vilakhanta (3rd Edition, November 2003)  
Page 355  
![](https://i.imgur.com/QeEjqeO.jpg)

**Comment by Sarabveer** [comment]
Depends on #95

**Comment by bhajneet** [comment]
Depends on #1480
