### ISSUE TITLE
CNXS - Gurbani Dian Laga Matra Di Vilakhanta

### ISSUE THREAD

**Issue by Sarabveer** [shabados/database#86]
| Key | Value |
| ---- | ------ |
| ID | CNXS |
| Shabad OS  | `syj sDw. shju Cwvwxu, sMqoKu srwiecau; sdw sIl sMnwhu sohY ]`  |
| Gurbani Dian Laga Matra Di Vilakhanta  |  `srwiecau` ≠ `srwie cau`  |

Gurbani Dian Laga Matra Di Vilakhanta (3rd Edition, November 2003)  
Page 359   
![](https://i.imgur.com/zgssX9b.jpg)

**Comment by Sarabveer** [comment]
Depends on #95

**Comment by bhajneet** [comment]
Depends on #1480
