### ISSUE TITLE
BPKY - Gurbani Dian Laga Matra Di Vilakhanta

### ISSUE THREAD

**Issue by Sarabveer** [shabados/database#87]
| Key | Value |
| ---- | ------ |
| ID | BPKY |
| Shabad OS  | `AkQ kQw Amrw purI; ijsu dyie su pwvY ]` |
| Gurbani Dian Laga Matra Di Vilakhanta  | `Amrw purI` ≠ `AmrwpurI`  |

Gurbani Dian Laga Matra Di Vilakhanta (3rd Edition, November 2003)  
Page 360  
![](https://i.imgur.com/oWCUz4n.jpg)

**Comment by Sarabveer** [comment]
| Key | Value |
| ---- | ------ |
| ID | BY65 |
| Shabad OS  | `goibMd vwlu, goibMd purI sm; jl´n. qIir ibpws bnwXau ]` |
| Gurbani Dian Laga Matra Di Vilakhanta  | `goibMd vwlu` ≠ `goibMdvwlu`  |

Gurbani Dian Laga Matra Di Vilakhanta (3rd Edition, November 2003)  
Page 366  

Page 367

**Comment by Sarabveer** [comment]
I think in general, city names should be together. Maybe a global replace can be done.

**Comment by Sarabveer** [comment]
Depends on #95

**Comment by bhajneet** [comment]
Depends on #1480
