### ISSUE TITLE
Single vs Double for Pauri endings?

### ISSUE THREAD

**Issue by bhajneet** [ShabadOS/database#874]
Should these all be single or double? In db we have single around the number. In proof it is double danda around each pauri number.

| Key | Value |
| --- | ----- |
View | https://database.shabados.com/sources/3/page/1/line/10
Source | Vaaran Bhai Gurdas Ji
Page | 1
ID | DXWF
Line | jyhw bIau, qyhw Plu pwieAw [1[

**Comment by Sarabveer** [comment]
For now single danda should be kept (for consistency), but need more research into this.
