### ISSUE TITLE
Store Database in RAM

### ISSUE THREAD

**Issue by bhajneet** [shabados/database#96]
To potentially speed things up for Shabad OS only boxes (such as gurdwara laptops/PCs) if they have enough RAM they should be given an option to store the entire DB in RAM.

**Comment by Sarabveer** [comment]
> 
> 
> Closing without resolution. This issue either affects too few users or there are too many issues with higher impact to be working on. It is possible to re-open or re-visit this issue at a later time. If you feel this issue is important, please give a thumbs-up reaction to the first post. You may track this issue from the pinned meta-tracker at the top of the issues home page.

@bhajneet in https://github.com/shabados/presenter/issues/99#issuecomment-653939117
