### ISSUE TITLE
Can custom characters for better rendering be added to ASCII font?

### ISSUE THREAD

**Issue by bhajneet** [ShabadOS/database#992]
| Key | Value |
| --- | ----- |
View | https://database.shabados.com/sources/3/page/6/line/150
Source | Vaaran Bhai Gurdas Ji
Page | 6
ID | LH7D
Line | sIsu invwey FINgulI; gil bMDy jlu aucw AwvY [

@Sarabveer is there a character for this? It's a bindi on the left side of gagga or a bindi past previous char without taking up whitespace below compare db viewer or https://unicode.sarabveer.me/ to image here:
![image](https://user-images.githubusercontent.com/14130567/65014143-af365b00-d8eb-11e9-9ffd-0556a4fc4cbd.png)

**Comment by Sarabveer** [comment]
`FINgulI`

**Comment by bhajneet** [comment]
So there is no character. Is there a way for us to add an ASCII character for this? It comes up a lot and looks better closer together rather than broken apart like in our font

![image](https://user-images.githubusercontent.com/14130567/66720982-3fbf6880-edd0-11e9-930b-2e2022b6c48d.png)

vs.

![image](https://user-images.githubusercontent.com/14130567/66720959-30401f80-edd0-11e9-85dd-bba7ea99dde6.png)

**Comment by Sarabveer** [comment]
This is just a font thing. It's not a big deal. Try the same thing in Unicode using the OpenSatlujUni font [here](https://unicode.sarabveer.com)

I would advise agaisnt modifying the ASCII Gurmukhi standard.

**Comment by Sarabveer** [comment]
I would advise against modifying the GurbaniAkhar ASCII standard.

I already tried this to create a new character (Horra with Bindi Underneath, from Talwara Ji's Saral Steek). This just created problems, as many people don't use our modified fonts.
